# codemagic.yaml

workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 120
    instance_type: linux # النوع الصحيح لبناء Android

    environment:
      # حذفت android_signing لأنك ما سجلت شهادة بعد
      groups:
        - env # المجموعة اللي فيها المتغيرات: EXPO_PUBLIC_SUPABASE_URL، EXPO_PUBLIC_SUPABASE_ANON_KEY، EXPO_PUBLIC_WA_ACCESS_TOKEN
      vars:
        # المتغيرات العامة (التي لا تحتاج إلى حماية)
        PACKAGE_NAME: "com.quqaz.AffairsEmployees" # اسم الحزمة من app.json

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Run Expo Prebuild
        script: |
          npx expo prebuild --clean

      - name: Install CocoaPods dependencies (Sometimes needed)
        script: |
          cd ios && pod install || echo "Pod install failed, but continuing... (This is okay if not building iOS in this workflow)"

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon

    artifacts:
      # رفع الملف بعد البناء
      - android/app/build/outputs/apk/release/app-release.apk

    publishing:
      email:
        recipients:
          - abrahim71192@gmail.com # بريدك
        notify:
          success: true
          failure: false
